# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c0cat_cpp <- function(mat, n_iter, output = "category") {
    .Call(`_nullcat_c0cat_cpp`, mat, n_iter, output)
}

curvecat_cpp <- function(mat, n_iter, output = "category") {
    .Call(`_nullcat_curvecat_cpp`, mat, n_iter, output)
}

r0cat_cpp <- function(mat, n_iter, output = "category") {
    .Call(`_nullcat_r0cat_cpp`, mat, n_iter, output)
}

swapcat_cpp <- function(mat, n_iter, output = "category") {
    .Call(`_nullcat_swapcat_cpp`, mat, n_iter, output)
}

tswapcat_cpp <- function(mat, n_iter, output = "category") {
    .Call(`_nullcat_tswapcat_cpp`, mat, n_iter, output)
}

